tap "aws/tap"
tap "caskroom/fonts"
tap "go-delve/delve"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "awscli"
brew "docker"
brew "figlet"
brew "fzf"
brew "jpeg"
brew "ghq"
brew "go"
brew "hub"
brew "jq"
brew "libao"
brew "libcue"
brew "libevent"
brew "lynx"
brew "mackup"
brew "mad"
brew "mas"
brew "nvm"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "zsh"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "docker"
cask "firefox"
cask "fliqlo"
cask "google-backup-and-sync"
cask "google-chrome-canary"
cask "google-japanese-ime"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "licecap"
cask "ngrok"
cask "pdf-expert"
cask "postman"
cask "slack"
cask "sublime-text"
cask "visual-studio-code"
mas "", id: 508368068
mas "Amphetamine", id: 937984704
mas "Day One", id: 1055511498
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835
